export const jobs = [
  {
    id: "1",
    role: "Junior Frontend Engineer",
    company: "Linear",
    logo: "L",
    logoColor: "from-violet-300 to-indigo-500",
    location: "Remote · EU",
    type: "Full-time",
    salary: "€45–60k",
    tags: ["React", "TypeScript", "0–2 yrs"],
    posted: "2h ago",
    hot: true,
    match: 87,
    category: "eng",
    description: `We're looking for a Junior Frontend Engineer to join our product team at Linear. You'll work on the core application, helping build the future of project management software used by thousands of teams worldwide.

This is a fully remote role within EU time zones. You'll collaborate closely with senior engineers and designers, shipping real features from day one.`,
    responsibilities: [
      "Build and maintain UI components in React and TypeScript",
      "Collaborate with designers to implement pixel-perfect interfaces",
      "Write clean, well-tested code with code reviews",
      "Participate in architecture discussions and planning sessions",
      "Help improve developer tooling and internal processes",
    ],
    requirements: [
      "1–2 years of experience with React and TypeScript",
      "Solid understanding of HTML, CSS, and browser fundamentals",
      "Experience with Git and collaborative development workflows",
      "Strong attention to detail and design sensibility",
      "Good written communication in English",
    ],
    niceToHave: [
      "Experience with Next.js or similar frameworks",
      "Familiarity with design systems or component libraries",
      "Open source contributions",
    ],
    about:
      "Linear is the tool that streamlines software projects, sprints, tasks, and bug tracking. It's designed for high-performance teams that value clarity over chaos.",
  },
  {
    id: "2",
    role: "Product Designer",
    company: "Notion",
    logo: "N",
    logoColor: "from-neutral-200 to-neutral-400",
    location: "Berlin · Hybrid",
    type: "Full-time",
    salary: "€55–75k",
    tags: ["Figma", "Design Systems", "1–3 yrs"],
    posted: "5h ago",
    hot: false,
    match: 73,
    category: "design",
    description: `Join Notion's Berlin team as a Product Designer. You'll own end-to-end design for key product surfaces, working alongside PMs and engineers to shape how millions of people organise their work and life.`,
    responsibilities: [
      "Own the design of product features from ideation to launch",
      "Create wireframes, prototypes, and high-fidelity mockups in Figma",
      "Contribute to and maintain the design system",
      "Run user research sessions and synthesise findings",
      "Partner with engineering to ensure quality implementation",
    ],
    requirements: [
      "1–3 years of product design experience",
      "Strong proficiency in Figma",
      "Portfolio demonstrating end-to-end product thinking",
      "Experience contributing to a design system",
      "Comfortable working in cross-functional teams",
    ],
    niceToHave: [
      "Experience with motion/animation design",
      "Background in information architecture",
      "Familiarity with accessibility standards",
    ],
    about:
      "Notion is the connected workspace for modern teams — notes, docs, databases, and projects all in one place.",
  },
  {
    id: "3",
    role: "Growth Marketing Associate",
    company: "Wise",
    logo: "W",
    logoColor: "from-emerald-300 to-teal-500",
    location: "Tallinn · On-site",
    type: "Full-time",
    salary: "€38–50k",
    tags: ["SEO", "Analytics", "Entry-level"],
    posted: "1d ago",
    hot: false,
    match: 64,
    category: "marketing",
    description: `Wise's Growth team is hiring a Marketing Associate to support acquisition campaigns across SEO, paid, and content. You'll work with data daily and have real ownership from the start.`,
    responsibilities: [
      "Support SEO content strategy and on-page optimisation",
      "Analyse campaign performance and report on key metrics",
      "Run A/B tests on landing pages and email sequences",
      "Coordinate with agencies and freelancers",
      "Research competitor activity and market trends",
    ],
    requirements: [
      "Degree in Marketing, Business, or related field (or equivalent experience)",
      "Basic understanding of SEO and Google Analytics",
      "Strong analytical mindset — comfortable with spreadsheets",
      "Excellent written English",
      "Organised, detail-oriented, self-starter",
    ],
    niceToHave: [
      "Experience with paid social or Google Ads",
      "Familiarity with HubSpot or similar CRM",
      "Basic SQL knowledge",
    ],
    about:
      "Wise is the global technology company building the best way to move money around the world — fast, cheap, and transparent.",
  },
  {
    id: "4",
    role: "Customer Success Manager",
    company: "Pleo",
    logo: "P",
    logoColor: "from-rose-300 to-pink-500",
    location: "Remote · Europe",
    type: "Full-time",
    salary: "€42–55k",
    tags: ["B2B SaaS", "1–3 yrs"],
    posted: "1d ago",
    hot: false,
    match: 91,
    category: "support",
    description: `Pleo is looking for a Customer Success Manager to own relationships with a portfolio of SMB accounts. You'll ensure customers get real value from the product and drive retention and expansion.`,
    responsibilities: [
      "Manage a book of 80–100 SMB accounts",
      "Run onboarding calls and quarterly business reviews",
      "Identify expansion and upsell opportunities",
      "Act as the voice of the customer internally",
      "Collaborate with Product and Support to resolve issues",
    ],
    requirements: [
      "1–3 years in a customer-facing B2B SaaS role",
      "Track record of hitting retention or NPS targets",
      "Strong empathy and communication skills",
      "Comfortable with CRM tools (Salesforce, HubSpot)",
      "Fluent English; additional European language a plus",
    ],
    niceToHave: [
      "Experience with spend management or fintech products",
      "Background in account management",
      "Data-driven approach to customer health",
    ],
    about:
      "Pleo is a spend management platform that gives companies a smarter way to handle expenses, cards, and invoices.",
  },
  {
    id: "5",
    role: "Data Analyst — Intern",
    company: "Bolt",
    logo: "B",
    logoColor: "from-lime-300 to-green-500",
    location: "Tallinn · Hybrid",
    type: "Internship",
    salary: "€1.8–2.4k/mo",
    tags: ["SQL", "Python", "Student"],
    posted: "2d ago",
    hot: false,
    match: 58,
    category: "eng",
    description: `A 4-month paid internship on Bolt's Growth Analytics team. You'll work with real production data to help the team understand driver supply, pricing efficiency, and market expansion.`,
    responsibilities: [
      "Query and analyse large datasets using SQL and Python",
      "Build and maintain dashboards in Tableau or Metabase",
      "Support A/B test design and analysis",
      "Present findings to stakeholders in weekly reviews",
      "Document data definitions and methodology",
    ],
    requirements: [
      "Currently studying in a quantitative field (CS, Stats, Economics, etc.)",
      "Solid SQL skills — can write complex queries independently",
      "Python basics (pandas, matplotlib)",
      "Strong analytical thinking and attention to detail",
      "Available for 4 months, full-time",
    ],
    niceToHave: [
      "Experience with dbt or data warehousing concepts",
      "Familiarity with Tableau, Metabase, or similar BI tools",
      "Previous internship in analytics",
    ],
    about:
      "Bolt is a transportation platform operating in 45+ countries, offering ride-hailing, scooters, food delivery, and car-sharing.",
  },
  {
    id: "6",
    role: "Junior Backend Developer",
    company: "Klarna",
    logo: "K",
    logoColor: "from-amber-200 to-orange-500",
    location: "Stockholm · Hybrid",
    type: "Full-time",
    salary: "€48–62k",
    tags: ["Node.js", "Postgres", "0–2 yrs"],
    posted: "3d ago",
    hot: false,
    match: 76,
    category: "eng",
    description: `Join Klarna's Payments Infrastructure team as a Junior Backend Developer. You'll work on high-throughput APIs that process millions of transactions daily, supported by a team of experienced engineers.`,
    responsibilities: [
      "Design and implement RESTful APIs in Node.js",
      "Write and optimise Postgres queries and migrations",
      "Participate in on-call rotation (light load for juniors)",
      "Contribute to system design discussions",
      "Write documentation and unit/integration tests",
    ],
    requirements: [
      "0–2 years of backend development experience",
      "Comfortable with Node.js and TypeScript",
      "Understanding of relational databases and SQL",
      "Familiar with REST API design principles",
      "Interest in distributed systems and scalability",
    ],
    niceToHave: [
      "Experience with Kafka or event-driven architecture",
      "Kubernetes or Docker familiarity",
      "Prior exposure to payments or fintech",
    ],
    about:
      "Klarna is a global payments and shopping service that makes checkout smoother, safer, and more flexible for consumers and merchants.",
  },
];

export const companies = [
  { name: "Linear", letter: "L", gradient: "from-violet-300 to-indigo-500", location: "San Francisco · Remote", openRoles: 3, tags: ["Engineering", "Design"] },
  { name: "Notion", letter: "N", gradient: "from-neutral-200 to-neutral-400", location: "San Francisco · Berlin", openRoles: 2, tags: ["Design", "Marketing"] },
  { name: "Wise", letter: "W", gradient: "from-emerald-300 to-teal-500", location: "London · Tallinn", openRoles: 4, tags: ["Marketing", "Engineering"] },
  { name: "Pleo", letter: "P", gradient: "from-rose-300 to-pink-500", location: "Copenhagen · Remote", openRoles: 2, tags: ["Customer Success", "Sales"] },
  { name: "Bolt", letter: "B", gradient: "from-lime-300 to-green-500", location: "Tallinn · Warsaw", openRoles: 5, tags: ["Engineering", "Data"] },
  { name: "Klarna", letter: "K", gradient: "from-amber-200 to-orange-500", location: "Stockholm · Berlin", openRoles: 3, tags: ["Engineering", "Finance"] },
  { name: "Veriff", letter: "V", gradient: "from-sky-300 to-blue-500", location: "Tallinn · Remote", openRoles: 4, tags: ["Engineering", "Operations"] },
  { name: "Revolut", letter: "R", gradient: "from-indigo-300 to-purple-500", location: "London · Kraków", openRoles: 6, tags: ["Engineering", "Compliance"] },
  { name: "Vinted", letter: "V", gradient: "from-teal-300 to-cyan-500", location: "Vilnius · Berlin", openRoles: 3, tags: ["Engineering", "Product"] },
  { name: "Glovo", letter: "G", gradient: "from-yellow-300 to-amber-500", location: "Barcelona · Remote", openRoles: 2, tags: ["Operations", "Marketing"] },
  { name: "Spotify", letter: "S", gradient: "from-green-300 to-emerald-600", location: "Stockholm · Remote", openRoles: 7, tags: ["Engineering", "Data", "Design"] },
  { name: "Skype", letter: "S", gradient: "from-blue-300 to-sky-500", location: "Tallinn · London", openRoles: 1, tags: ["Engineering"] },
];

export type Job = typeof jobs[0];
export type Company = typeof companies[0];
